<a href="https://colab.research.google.com/github/IrumShehryar/ML-NLP-Coursework/blob/main/machine-learning/classification/Project_01_Getting_Class_Probabilities.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

# Generating Data Indicating the Size of Tumor

In [2]:
# Reshaped for Logistic function.

X = np.array([3.77, 2.47, 2.19, 0.21, 1.63, 1.69, 5.09, 4.23, 5.02, 4.41, 4.729, 6.01])
y = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

### X is the size of tumor.
### y is 0 or 1. 0 means no cancer and 1 means cancer

In [3]:
df = pd.DataFrame({'X' : X, 'y' : y})
df

        X  y
0   3.770  0
1   2.470  0
2   2.190  0
3   0.210  0
4   1.630  0
5   1.690  0
6   5.090  1
7   4.230  1
8   5.020  1
9   4.410  1
10  4.729  1
11  6.010  1

# Applying Logistic Regression (Train the Model)

In [4]:
X.shape

(12,)

In [5]:
X = X.reshape(-1,1)
X

array([[3.77 ],
       [2.47 ],
       [2.19 ],
       [0.21 ],
       [1.63 ],
       [1.69 ],
       [5.09 ],
       [4.23 ],
       [5.02 ],
       [4.41 ],
       [4.729],
       [6.01 ]])

In [6]:
X.shape

(12, 1)

In [7]:
log_reg = LogisticRegression()
LR = log_reg.fit(X,y)

# Generate unseen value (Test Sample)

In [9]:
X_test = np.array([3.50]).reshape(-1,1)
X_test

array([[3.5]])

# Getting Probabilities of prediction

In [10]:
LR.predict_proba(X_test)

array([[0.54112337, 0.45887663]])

# Getting  class prediction

In [11]:
y_pred = LR.predict(X_test)

In [12]:
y_pred

array([0])

# Generating Another Dataset

In [13]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

In [14]:
X, y = make_classification(n_samples = 50, n_features = 2, n_informative = 2, n_redundant = 0,  n_classes = 2, random_state = 42)

In [15]:
X

array([[ 1.24228249,  1.12818953],
       [-0.48950622,  1.58014031],
       [-1.56613543,  1.94780225],
       [-0.73346488, -0.99441099],
       [-0.91528051, -1.33494489],
       [ 0.75671589,  0.84753652],
       [-1.17172684,  1.81192736],
       [-0.03666101,  0.22371669],
       [ 0.5753018 , -1.0517062 ],
       [-0.59118479, -0.56937358],
       [ 0.13044668, -0.88863141],
       [ 1.7867177 ,  1.22036473],
       [-0.57481614,  0.07203808],
       [ 1.0939436 , -1.54301962],
       [ 0.80846457, -0.33941174],
       [-1.94237711,  1.75036033],
       [-0.51310348,  0.41464132],
       [ 0.89147389,  1.21488869],
       [ 0.7290478 , -0.727392  ],
       [-1.35996395,  0.95897538],
       [ 1.23051266, -2.33675611],
       [ 0.33094931,  0.8534947 ],
       [-1.23116192, -0.97692815],
       [-2.12694133, -1.84430824],
       [-0.53914228, -1.07161518],
       [ 0.64027585,  0.88603341],
       [ 1.21524433,  1.10091916],
       [ 0.91863304, -1.11375934],
       [-1.85460906, -2.26489668],
       [ 0.7355718 ,  0.78204653],
       [ 1.55953222, -2.00545325],
       [-1.45005871,  0.19537765],
       [ 0.21344413, -0.31725458],
       [-1.63835161,  0.9429    ],
       [-1.81054868,  2.45690167],
       [ 2.80439509,  1.85478373],
       [ 0.16263743, -0.76187349],
       [-0.33851292,  0.30469933],
       [ 1.58307723,  1.14486264],
       [-3.87991911,  2.47468454],
       [-1.42253587,  2.32395437],
       [ 0.14129631, -0.28759161],
       [-1.7412594 , -1.07044214],
       [ 0.06415523,  0.58263943],
       [-0.90661532,  2.03277013],
       [ 1.59211088, -1.3683148 ],
       [ 1.54957192, -2.16913469],
       [-0.79382063, -0.78331588],
       [ 1.96485511, -1.46339248],
       [ 2.51170023,  1.63193607]])

In [16]:
np.unique(y)

array([0, 1])

In [17]:
X.shape

(50, 2)

# Perform a train test split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

# Applying Logistic Regression

In [19]:
model = LogisticRegression()
LR = model.fit(X_train, y_train)

# Getting Probabilities and Predictions from X_test

In [20]:
y_pred_prob = LR.predict_proba(X_test).round(2)
y_pred_prob

array([[0.06, 0.94],
       [1.  , 0.  ],
       [0.02, 0.98],
       [0.02, 0.98],
       [0.14, 0.86],
       [0.01, 0.99],
       [0.07, 0.93],
       [0.22, 0.78],
       [0.4 , 0.6 ],
       [0.97, 0.03]])

In [21]:
y_pred_prob[:,1]

array([0.94, 0.  , 0.98, 0.98, 0.86, 0.99, 0.93, 0.78, 0.6 , 0.03])

# Getting Class Predictions

In [22]:
y_pred = LR.predict(X_test)
y_pred

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 0])

# Observing Probabilities and Class Predictions

In [23]:
df = pd.DataFrame({"Prob_class_0": y_pred_prob[:,0]
,"Prob_class_1": y_pred_prob[:,1]
,"Predicted class": y_pred})
df

   Prob_class_0  Prob_class_1  Predicted class
0          0.06          0.94                1
1          1.00          0.00                0
2          0.02          0.98                1
3          0.02          0.98                1
4          0.14          0.86                1
5          0.01          0.99                1
6          0.07          0.93                1
7          0.22          0.78                1
8          0.40          0.60                1
9          0.97          0.03                0