<a href="https://colab.research.google.com/github/IrumShehryar/ML-NLP-Coursework/blob/main/nlp/04-neural-network/markov-model-for-text-generation/Project01_TextGeneration_by_Transition_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [1]:
import random
import numpy as np
import pandas as pd

# Create the text

In [2]:
text = " The quick brown fox jumps over the lazy dog and the quick white cat jumps over the lazy rabbit "

# Adding start and end tokens to the text

In [3]:
text = "<start>" + text  +  "<end>"

In [4]:
text

'<start> The quick brown fox jumps over the lazy dog and the quick white cat jumps over the lazy rabbit <end>'

# Tokenize the text

In [5]:
tokens = text.lower().split()

In [6]:
tokens

['<start>',
 'the',
 'quick',
 'brown',
 'fox',
 'jumps',
 'over',
 'the',
 'lazy',
 'dog',
 'and',
 'the',
 'quick',
 'white',
 'cat',
 'jumps',
 'over',
 'the',
 'lazy',
 'rabbit',
 '<end>']

# Build the vocab

In [7]:
vocab = list(set(tokens))

In [8]:
vocab

['jumps',
 'fox',
 'dog',
 'and',
 'over',
 'white',
 'the',
 '<start>',
 'rabbit',
 'lazy',
 '<end>',
 'brown',
 'quick',
 'cat']

In [9]:
vocab.sort()

In [10]:
vocab

['<end>',
 '<start>',
 'and',
 'brown',
 'cat',
 'dog',
 'fox',
 'jumps',
 'lazy',
 'over',
 'quick',
 'rabbit',
 'the',
 'white']

# Count how many times the word occurs in vocab

In [11]:
word_occurrences = {}

for token in vocab:
    word_occurrences[token] = tokens.count(token)

word_occurrences

{'<end>': 1,
 '<start>': 1,
 'and': 1,
 'brown': 1,
 'cat': 1,
 'dog': 1,
 'fox': 1,
 'jumps': 2,
 'lazy': 2,
 'over': 2,
 'quick': 2,
 'rabbit': 1,
 'the': 4,
 'white': 1}

# Build a transition Matrix

In [12]:
transition_matrix = pd.DataFrame(
    np.zeros([len(vocab), len(vocab)]),
    columns=vocab,
    index=vocab
)

In [13]:
transition_matrix

,<end>,<start>,and,brown,cat,dog,fox,jumps,lazy,over,quick,rabbit,the,white
<end>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
<start>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
and,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
brown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
cat,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
dog,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
fox,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
jumps,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
lazy,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
over,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
quick,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
rabbit,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
the,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
white,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Fill the Transition Matrix

In [14]:
for index, token in enumerate(tokens):
    try:
        transition_matrix.loc[token, tokens[index+1]] += 1
        print(token, tokens[index+1])
        print(transition_matrix.loc[token, tokens[index+1]])
        print(" ")
    except IndexError:
        print('Reached end of the text!')

<start> the
1.0

the quick
1.0

quick brown
1.0

brown fox
1.0

fox jumps
1.0

jumps over
1.0

over the
1.0

the lazy
1.0

lazy dog
1.0

dog and
1.0

and the
1.0

the quick
2.0

quick white
1.0

white cat
1.0

cat jumps
1.0

jumps over
2.0

over the
2.0

the lazy
2.0

lazy rabbit
1.0

rabbit <end>
1.0

Reached end of the text!

In [15]:
transition_matrix

,<end>,<start>,and,brown,cat,dog,fox,jumps,lazy,over,quick,rabbit,the,white
<end>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
<start>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
and,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
brown,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
cat,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
dog,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
fox,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
jumps,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
lazy,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
over,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
quick,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
rabbit,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
the,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0
white,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Convert Transition Matrix into Probabilities

In [16]:
for word in vocab:
    transition_matrix.loc[word,:] /= word_occurrences[word]

In [17]:
transition_matrix

,<end>,<start>,and,brown,cat,dog,fox,jumps,lazy,over,quick,rabbit,the,white
<end>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
<start>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
and,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
brown,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
cat,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
dog,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
fox,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
jumps,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
lazy,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0
over,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
quick,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5
rabbit,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
the,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.5,0.0,0.0,0.0
white,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Generate Text

In [18]:
def get_next_token(token, transition_matrix):
    return transition_matrix.loc[token].sort_values().tail(1).index[0]

In [23]:
sentence = ''
token = 'lazy'  #change starting token

In [24]:
i = 0
while i < 20:
    sentence += token + ' '

    pred_token = get_next_token(token, transition_matrix)
    token = pred_token

    i += 1

In [25]:
sentence

'lazy rabbit <end> white cat jumps over the lazy rabbit <end> white cat jumps over the lazy rabbit <end> white '

# Limitations

### Using only the Transition Matrix, we observe the lot of repetiions. This is due to the fact that we are using very few resources i.e only the Transition Matrix and the one previous word.