<a href="https://colab.research.google.com/github/IrumShehryar/ML-NLP-Coursework/blob/main/nlp/neural-network/word-embeddings/Project02_Word_Vectors_Intuition_CoocurrenceMatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from sklearn.metrics.pairwise import cosine_similarity

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

# Generate some sentences

In [2]:
sentences = ['I purchased a bus',
             'I drive a bus',
             'I drove a bus',
             'I drove a truck',
             'He drove a truck',
            'He purchased a bus',
             'She drove a bus',
             'She drove a car',
             'He drives a car',
             'They drive a car',
             'They drive a bus',
             'They drive a truck']

# Create one hot encoder matrix

In [3]:
bag_of_words = ' '.join(sentences).lower() # join all sentences together

In [4]:
bag_of_words

'i purchased a bus i drive a bus i drove a bus i drove a truck he drove a truck he purchased a bus she drove a bus she drove a car he drives a car they drive a car they drive a bus they drive a truck'

In [5]:
set(bag_of_words.split(' '))

{'a',
 'bus',
 'car',
 'drive',
 'drives',
 'drove',
 'he',
 'i',
 'purchased',
 'she',
 'they',
 'truck'}

In [6]:
vocab = list(set(bag_of_words.split(' ')))

In [7]:
vocab.sort()

In [8]:
vocab

['a',
 'bus',
 'car',
 'drive',
 'drives',
 'drove',
 'he',
 'i',
 'purchased',
 'she',
 'they',
 'truck']

In [9]:
pd.DataFrame(np.identity(len(vocab)), index = vocab) # identity matrix

            0    1    2    3    4    5    6    7    8    9    10   11
a          1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
bus        0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
car        0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
drive      0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
drives     0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
drove      0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
he         0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
i          0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
purchased  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
she        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
they       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
truck      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

# Create Co_Ocurrence Matrix by selecting one neighbor around the word

In [ ]:
tokenized_sentences = []
for sentence in sentences:
  tokenized_sentences.append(word_tokenize(sentence.lower()))

In [11]:
import nltk
nltk.download('punkt_tab')
tokenized_sentences=[]
for sentence in sentences:
  tokenized_sentences.append(word_tokenize(sentence.lower()))
tokenized_sentences

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

[['i', 'purchased', 'a', 'bus'],
 ['i', 'drive', 'a', 'bus'],
 ['i', 'drove', 'a', 'bus'],
 ['i', 'drove', 'a', 'truck'],
 ['he', 'drove', 'a', 'truck'],
 ['he', 'purchased', 'a', 'bus'],
 ['she', 'drove', 'a', 'bus'],
 ['she', 'drove', 'a', 'car'],
 ['he', 'drives', 'a', 'car'],
 ['they', 'drive', 'a', 'car'],
 ['they', 'drive', 'a', 'bus'],
 ['they', 'drive', 'a', 'truck']]

In [ ]:
tokenized_sentences

In [12]:
vocab_size = len(vocab)

In [13]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [14]:
%cd /content/drive/MyDrive/NLP-course/Course Material/Word Embeddings

/content/drive/MyDrive/NLP-course/Course Material/Word Embeddings

In [15]:
from co_ocurrence_matrix import Co_Ocurrence_Matrix

In [16]:
co_ocurrenceMatrix = Co_Ocurrence_Matrix(vocab, vocab_size, tokenized_sentences)

In [17]:
co_ocurrenceMatrix = pd.DataFrame(co_ocurrenceMatrix, index=vocab, columns = vocab)

In [18]:
co_ocurrenceMatrix

,a,bus,car,drive,drives,drove,he,i,purchased,she,they,truck
a,0.0,6.0,3.0,4.0,1.0,5.0,0.0,0.0,2.0,0.0,0.0,3.0
bus,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
car,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
drive,4.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0
drives,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
drove,5.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,2.0,0.0,0.0
he,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
i,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0
purchased,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
she,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
they,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
truck,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Calculate Cosine Similarity between the Words

In [19]:
cosine_Similarity = pd.DataFrame(cosine_similarity(co_ocurrenceMatrix), index=vocab, columns = vocab)

In [20]:
cosine_Similarity

,a,bus,car,drive,drives,drove,he,i,purchased,she,they,truck
a,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.461880,0.653197,0.000000,0.500000,0.400000,0.000000
bus,0.000000,1.000000,1.000000,0.784465,0.707107,0.857493,0.000000,0.000000,0.816497,0.000000,0.000000,1.000000
car,0.000000,1.000000,1.000000,0.784465,0.707107,0.857493,0.000000,0.000000,0.816497,0.000000,0.000000,1.000000
drive,0.000000,0.784465,0.784465,1.000000,0.554700,0.739940,0.000000,0.000000,0.720577,0.000000,0.000000,0.784465
drives,0.000000,0.707107,0.707107,0.554700,1.000000,0.727607,0.000000,0.000000,0.866025,0.000000,0.000000,0.707107
drove,0.000000,0.857493,0.857493,0.739940,0.727607,1.000000,0.000000,0.000000,0.910182,0.000000,0.000000,0.857493
he,0.461880,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.707107,0.000000,0.577350,0.000000,0.000000
i,0.653197,0.000000,0.000000,0.000000,0.000000,0.000000,0.707107,1.000000,0.000000,0.816497,0.408248,0.000000
purchased,0.000000,0.816497,0.816497,0.720577,0.866025,0.910182,0.000000,0.000000,1.000000,0.000000,0.000000,0.816497
she,0.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.577350,0.816497,0.000000,1.000000,0.000000,0.000000
they,0.400000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.408248,0.000000,0.000000,1.000000,0.000000
truck,0.000000,1.000000,1.000000,0.784465,0.707107,0.857493,0.000000,0.000000,0.816497,0.000000,0.000000,1.000000

# Find the analogies of the words

In [21]:
def find_similar_words(word):
    return cosine_Similarity.loc[word].sort_values(ascending=False).head(3)

In [22]:
find_similar_words('bus')

bus      1.0
car      1.0
truck    1.0
Name: bus, dtype: float64

In [23]:
find_similar_words('car')

bus      1.0
car      1.0
truck    1.0
Name: car, dtype: float64

In [24]:
find_similar_words('drive')

drive    1.000000
bus      0.784465
car      0.784465
Name: drive, dtype: float64

In [25]:
find_similar_words('drove')

drove        1.000000
purchased    0.910182
bus          0.857493
Name: drove, dtype: float64